name: 'push CI'

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json kubernetes/"
  validate-k8s:
    needs: kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run kube-score
        run: |
          docker pull zegl/kube-score:latest
          docker run -v $(pwd):/project zegl/kube-score:latest score app/*.yaml

