name: 'push CI'

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

jobs:
  kubeconform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: kubeconfigs

    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json kubeconfigs/"

